services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: appf
    restart: always
    env_file:
      - .env
    