services:
  db:
    image: postgres:17
    restart: always
  env_file:
    - .env
  
  api:
    image: $app?Variable not set
    build:
      context: ./app
    restart: always
  env_file:
    - .env
  